version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "cf:7c:5e:b3:3d:69:ba:6a:23:f1:36:03:fb:e6:6f:f1"
      - run:
          name: Deploy Over SSH
          command: ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "sudo /var/www/scheduler/reload.sh"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master